### ISSUE TITLE
Well I wanted to play but it doesn't work

### ISSUE THREAD

**Issue by SeezoCode** [STOKYS/Strategy-Game#1]
Hey, 

Im a frontend developer over at my house and there happened a mishmash. So anyways today I had a dull burger for breakfast that really inspired me to tryout this Wars of Ages competitor. (provided I didn't misjudge it's predecessor and it isn't based on a completely different game than what I envisioned)

When I saw a release, I was thrilled to see what has been going on behind the scenes that I didn't know about. The idea of competition for such a complex game as Wars of Ages is, sounds really amazing. It may even happen that this game will be like twice as good (or even more) as the original reference game.

To get back to the problem of this yet-in-development-game or as someone else might call it alpha, or as I would call it pre-alpha game, a slight inconvenience has happened. When I try to play, the game invites me with it's pretty UI that, for the reason of this proposed issue, doesn't do any thing. It just contentedly hangs there as nothing had just been pressed. It even sounds like it constantly scoffs at me for spending my life in front of the computer instead of going out with the girls or having fun with the guys at a bar (or better yet, asking _her_ out to see a movie to get her).

It just doesn't work like that... I truly believe in this strong competition from a different side but it just will not happen as of yet.

**Proposed fix:** Make the buttons do stuff...

**Steps to replicate:** Open the site and click a button. You will be impressed.

Better ways to communicate instead of messaging apps: use GitHub.

**Comment by STOKYS** [comment]
Bruh

**Comment by STOKYS** [comment]
We are deeply sorry for the inconvenience, we hope to make the game playable (someday) but not now.

As a sorry, our CEO personally send to your Steam library games such as NEKOPARA Vol. 0 and 1, please the gift and our sincerest apologies.

Thank you.

**Comment by SeezoCode** [comment]
Thank you kind sir
